# Generated by Django 5.2.6 on 2025-09-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='username',
        ),
    ]
