# Generated by Django 5.2.6 on 2025-09-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mainuser_options_alter_mainuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainUser',
        ),
    ]
