# Generated by Django 5.2.6 on 2025-09-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mainuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='rut',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userrol',
            name='namerol',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
