# Generated by Django 5.2.6 on 2025-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mainuser_birthday_alter_mainuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
