# Generated by Django 5.2.6 on 2025-09-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mainuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='rut',
        ),
    ]
