# Generated by Django 5.2.6 on 2025-09-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_mainuser_birthday_remove_mainuser_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
