# Generated by Django 5.2.6 on 2025-09-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mainuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
