# Generated by Django 5.2.6 on 2025-11-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_empleados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='segundo_nombre',
        ),
    ]
