# Generated by Django 5.2.6 on 2025-11-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_empleados_segundo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
