# Generated by Django 5.2.6 on 2025-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_empleados_segundo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_reserva_hora', models.TimeField()),
                ('horario_reserva_expiracion', models.TimeField()),
            ],
        ),
    ]
