# Generated by Django 5.2.6 on 2025-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_horariosreserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosreserva',
            name='horario_reserva_expiracion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariosreserva',
            name='horario_reserva_hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
