# Generated by Django 5.2.6 on 2025-11-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_horariosreserva_horario_reserva_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosreserva',
            name='horario_reserva_termino',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
