# Generated by Django 5.2.6 on 2025-11-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_horariosreserva_horario_reserva_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reserva_nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservasCanchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('reserva_precio', models.IntegerField()),
                ('reserva_fecha', models.DateField(blank=True, null=True)),
                ('estado_reserva_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadosreserva')),
                ('horario_reserva_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.horariosreserva')),
            ],
        ),
    ]
