# Generated by Django 5.2.6 on 2025-11-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_estadosreserva_reservascanchas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservascanchas',
            old_name='estado_reserva_id',
            new_name='estado_reserva',
        ),
        migrations.RenameField(
            model_name='reservascanchas',
            old_name='horario_reserva_id',
            new_name='horario_reserva',
        ),
        migrations.AddField(
            model_name='reservascanchas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
