# Generated by Django 5.2.6 on 2025-11-11 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_estado_reserva_id_reservascanchas_estado_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservascanchas',
            name='cancha_deportiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.canchas'),
        ),
    ]
