# Generated by Django 5.2.6 on 2025-11-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reservascanchas_cancha_deportiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='canchas',
            name='cancha_precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
