# Generated by Django 5.2.6 on 2025-11-18 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_canchas_cancha_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_mantencion_nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoCanchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantencion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_proxima_mantencion', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_mantencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadosmantencion')),
                ('numero_cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.canchas')),
            ],
        ),
    ]
