# Generated by Django 5.2.6 on 2025-11-18 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_estadosmantencion_mantenimientocanchas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimientocanchas',
            old_name='numero_cancha',
            new_name='cancha_deportiva',
        ),
        migrations.RenameField(
            model_name='mantenimientocanchas',
            old_name='descripcion',
            new_name='mantencion_descripcion',
        ),
        migrations.RenameField(
            model_name='mantenimientocanchas',
            old_name='fecha_mantencion',
            new_name='mantencion_fecha',
        ),
        migrations.RenameField(
            model_name='mantenimientocanchas',
            old_name='observaciones',
            new_name='mantencion_observaciones',
        ),
        migrations.RenameField(
            model_name='mantenimientocanchas',
            old_name='fecha_proxima_mantencion',
            new_name='mantencion_proxima_fecha',
        ),
        migrations.AddField(
            model_name='mantenimientocanchas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
