# Generated by Django 5.2.6 on 2025-11-20 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_numero_cancha_mantenimientocanchas_cancha_deportiva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_gastos_nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_gastos_nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos_fecha', models.DateField()),
                ('gastos_descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('gastos_proveedor', models.CharField(blank=True, max_length=250, null=True)),
                ('gastos_factura', models.IntegerField()),
                ('gastos_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gastos_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gastos_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gastos_mediodepago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria_gastos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriasgastos')),
                ('estados_gastos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadosgastos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
