# Generated by Django 5.2.6 on 2025-11-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_categoriasgastos_estadosgastos_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='gastos_mediodepago',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
