# Generated by Django 5.2.6 on 2025-11-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_gastos_gastos_mediodepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='gastos_factura',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
