# Generated by Django 5.2.6 on 2025-11-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_gastos_gastos_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservascanchas',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
